# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7c29b1a3e5cc5b8e697b1be490695d420fd6d12243abd7055373ab29ea4c7d8deb72fb9dc78b2f89c7f1fdcdaef9ed4f98e507a6adb8bc8aa982dd6d4ee7d5

test:
  secret_key_base: 35eda09721f00e62c931e8534facd668f735613b37f3669cb4cd718ac739c0b0fdc69e2cb56c19111fd918942f9397c9d72638dd09eb19485f9e8159881ffe7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
